adding check of emacs can parse the ~/.emacs file

diff --git a/setup-dotfiles b/setup-dotfiles
--- a/setup-dotfiles
+++ b/setup-dotfiles
@@ -13,3 +13,13 @@ echo   Initializing Git submodules, this may take a while...
 echo 
 git submodule init
 git submodule update
+
+# check if emacs can parse the '~/.emacs' file
+echo "Checking if ~/.emacs can be read by your emacs..."
+emacs -Q --batch -l ~/.emacs
+if [ $? -ne 0 ]; then
+  echo "your Emacs can't parse the init file correctly, fix it!"
+  exit 1
+else
+  echo "Your Emacs is ready to use. Enjoy!"
+fi
